version: "1.0"
services:
  # mlflow_server:
  #   image: mle_decathlon:model_repository.latest
  #   container_name: model_repository
  #   build:
  #     context: .
  #     dockerfile: modules/model_training/Dockerfile
  trainer:
    image: mle_decathlon:trainer.latest
    container_name: trainer
    build:
      context: .
      dockerfile: modules/model_training/Dockerfile