FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml .

RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction

COPY . .

# CMD ["python", "train.py"]
RUN python train.py